-- USERS
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (1, 'john.doe', 'john.doe@customer.com', 'password123', 'John Doe', 'CUSTOMER', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (2, 'jane.smith', 'jane.smith@customer.com', 'password123', 'Jane Smith', 'CUSTOMER', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (3, 'bob.johnson', 'bob.johnson@customer.com', 'password123', 'Bob Johnson', 'CUSTOMER', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (4, 'alice.cooper', 'alice.cooper@customer.com', 'password123', 'Alice Cooper', 'CUSTOMER', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (5, 'agent.alice', 'alice@support.com', 'password123', 'Alice Williams', 'AGENT', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (6, 'agent.charlie', 'charlie@support.com', 'password123', 'Charlie Brown', 'AGENT', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (7, 'agent.david', 'david@support.com', 'password123', 'David Martinez', 'AGENT', 1, SYSDATE);

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD_HASH, FULL_NAME, ROLE, IS_ACTIVE, CREATED_AT)
VALUES (8, 'admin', 'admin@support.com', 'password123', 'System Administrator', 'ADMIN', 1, SYSDATE);

-- CATEGORIES
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (1, 'Technical Support', 'Technical issues and bugs', 1);

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (2, 'Billing', 'Payment and subscription issues', 1);

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (3, 'Account Management', 'Account access and profile', 1);

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (4, 'Product Inquiry', 'Questions about products', 1);

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (5, 'Feature Request', 'New feature suggestions', 1);

INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, IS_ACTIVE)
VALUES (6, 'General', 'General inquiries', 1);

-- PRIORITIES
INSERT INTO PRIORITIES (ID, NAME, PRIORITY_LEVEL, DESCRIPTION)
VALUES (1, 'LOW', 1, 'Low priority');

INSERT INTO PRIORITIES (ID, NAME, PRIORITY_LEVEL, DESCRIPTION)
VALUES (2, 'MEDIUM', 2, 'Medium priority');

INSERT INTO PRIORITIES (ID, NAME, PRIORITY_LEVEL, DESCRIPTION)
VALUES (3, 'HIGH', 3, 'High priority');

INSERT INTO PRIORITIES (ID, NAME, PRIORITY_LEVEL, DESCRIPTION)
VALUES (4, 'CRITICAL', 4, 'Critical priority');

-- STATUSES
INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (1, 'OPEN', 'Ticket is open', 0);

INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (2, 'IN_PROGRESS', 'Ticket in progress', 0);

INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (3, 'WAITING_CUSTOMER', 'Waiting for customer', 0);

INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (4, 'ON_HOLD', 'Ticket on hold', 0);

INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (5, 'RESOLVED', 'Ticket resolved', 1);

INSERT INTO STATUSES (ID, NAME, DESCRIPTION, IS_FINAL)
VALUES (6, 'CLOSED', 'Ticket closed', 1);

-- TICKETS
INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (1, 'Cannot login to account', 'I cannot login. Getting error message.', 1, NULL, 1, 3, 1, SYSDATE, SYSDATE);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (2, 'Charged twice', 'I was charged twice for subscription.', 2, 5, 2, 4, 2, SYSDATE - 2, SYSDATE - 1);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT, RESOLVED_AT)
VALUES (3, 'Update email address', 'Need to change my email address.', 3, 6, 3, 1, 5, SYSDATE - 5, SYSDATE - 3, SYSDATE - 3);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (4, 'API integration question', 'Does your product support REST API?', 2, NULL, 4, 2, 1, SYSDATE - 1, SYSDATE - 1);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (5, 'App crashes on startup', 'Application crashes immediately.', 1, 5, 1, 3, 3, SYSDATE - 3, SYSDATE - 1);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (6, 'Add dark mode', 'Please add dark mode to mobile app.', 4, NULL, 5, 2, 1, SYSDATE - 4, SYSDATE - 4);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT)
VALUES (7, 'Data sync failing', 'Data not syncing between devices.', 3, 7, 1, 4, 2, SYSDATE - 1, SYSDATE);

INSERT INTO TICKETS (ID, TITLE, DESCRIPTION, CUSTOMER_ID, ASSIGNED_AGENT_ID, CATEGORY_ID, PRIORITY_ID, STATUS_ID, CREATED_AT, UPDATED_AT, RESOLVED_AT)
VALUES (8, 'Cannot download invoice', 'Invoice download link not working.', 4, 6, 2, 1, 6, SYSDATE - 7, SYSDATE - 5, SYSDATE - 5);

COMMIT;

-- Step 2: Fix sequences to start AFTER manual inserts
-- ============================================

-- Drop and recreate sequences with correct starting values
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE user_sequence';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE user_sequence START WITH 9 INCREMENT BY 1';

    EXECUTE IMMEDIATE 'DROP SEQUENCE category_sequence';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE category_sequence START WITH 7 INCREMENT BY 1';

    EXECUTE IMMEDIATE 'DROP SEQUENCE priority_sequence';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE priority_sequence START WITH 5 INCREMENT BY 1';

    EXECUTE IMMEDIATE 'DROP SEQUENCE status_sequence';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE status_sequence START WITH 7 INCREMENT BY 1';

    EXECUTE IMMEDIATE 'DROP SEQUENCE ticket_sequence';
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ticket_sequence START WITH 9 INCREMENT BY 1';

    DBMS_OUTPUT.PUT_LINE('Test data loaded and sequences fixed successfully!');
END;
/
